Feat : post page
ebokyung/eggplant-market-react pull request #63
Opened 2023-10-17 08:14 UTC by jypark38

### 🤚 잠깐!
- [ ] PR 제목 형식 확인 [`feat: 기능 추가`]
- [ ] 이슈 등록 확인
- [ ] 라벨 등록 확인

## ✏️ PR 요약
- [x] 기능 추가 : post 관련 기능
- [ ] 마크업 & 스타일 :
- [ ] 리팩토링 :
- [ ] 문서 수정 :
- [ ] 버그 수정 :
- [ ] 도와주세요 :
- [ ] 개발 환경 세팅 :

<br>

## 💡 상세 작업 내용

- get 요청 후 뿌리기
- 댓글 기능
- 댓글 제출하면 데이터 갱신

<br>

## 🌟 전달 사항

- 작동 gif

![게시글 상세](https://github.com/ebokyung/eggplant-market-react/assets/126536351/977a4109-a972-4cd8-8014-d09511f1a606)

- 댓글 제출 한번만 되게 했서요

<br>

## ⚠️ Issue Number
- #37 

<br><br>

2023-10-24 04:49 UTC, ebokyung commented on src/pages/Post/components/CommentInput.jsx
> +    <footer onSubmit={e => handleClick(e)} className="comment-section">
onSubmit을 Form이 아니라 footer에 넣어야 원하는 결과로 작동하나요?

2023-10-24 04:49 UTC, ebokyung commented on src/pages/Post/components/CommentInput.jsx
> +  };
isSubmitting 상태는 어떤 이유로 필요한건지 궁금해요

2023-10-24 07:09 UTC, jypark38 commented on src/pages/Post/components/CommentInput.jsx
> +  };
업로드 이벤트를 원래 디바운스로 처리하려 했는데 약간,, 불안정한거 같아서
isSubmitting 을 두고 위 코드처럼 작성하면 업로드 여러번 요청가는거 막힘니다

2023-10-24 07:09 UTC, jypark38 commented on src/pages/Post/components/CommentInput.jsx
> +    <footer onSubmit={e => handleClick(e)} className="comment-section">
이건 확인해보겠습니다 ㅜ

2023-10-25 06:52 UTC, jypark38 commented
일단 생각나는대로 revoke 처리를 해두었는데, 이렇게 하는게 맞는지 모르겠슴니다..

2023-10-25 06:54 UTC, jypark38 commented on src/pages/Post/components/CommentInput.jsx
> +    <footer onSubmit={e => handleClick(e)} className="comment-section">
왜 저기다 넣어놨지.. 바꿔놓겠슴니다

2023-10-25 11:28 UTC, ebokyung requested changes
다음 예시처럼 임시로 만든 url 자체를 전달해주어야합니다!
```
const temporaryURL = URL.createObjectURL(someFile);
URL.revokeObjectURL(temporaryURL);
```

2023-10-26 10:28 UTC, merged